/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#f3f3f4',
        'tertiary-fixed-dim': '#c3c7c9',
        'primary-fixed-dim': '#a1d1b4',
        'tertiary-fixed': '#e0e3e5',
        'secondary': '#555f71',
        'primary-container': '#1a4731',
        'outline': '#717972',
        'on-surface': '#1a1c1c',
        'on-tertiary': '#ffffff',
        'tertiary': '#262a2c',
        'surface': '#f9f9f9',
        'on-background': '#1a1c1c',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'surface-container': '#eeeeee',
        'on-primary': '#ffffff',
        'on-tertiary-fixed-variant': '#434749',
        'on-error-container': '#93000a',
        'inverse-on-surface': '#f0f1f1',
        'secondary-fixed-dim': '#bdc7dc',
        'secondary-fixed': '#d9e3f9',
        'on-secondary': '#ffffff',
        'surface-container-highest': '#e2e2e2',
        'primary': '#00301c',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed': '#121c2c',
        'background': '#f9f9f9',
        'on-tertiary-fixed': '#181c1e',
        'error-container': '#ffdad6',
        'surface-bright': '#f9f9f9',
        'surface-variant': '#e2e2e2',
        'outline-variant': '#c1c9c1',
        'on-primary-fixed': '#002112',
        'secondary-container': '#d6e0f6',
        'primary-fixed': '#bdeecf',
        'surface-dim': '#dadada',
        'on-secondary-fixed-variant': '#3d4759',
        'surface-tint': '#3b674f',
        'on-primary-fixed-variant': '#234f38',
        'tertiary-container': '#3c4042',
        'surface-container-high': '#e8e8e8',
        'inverse-primary': '#a1d1b4',
        'on-surface-variant': '#414943',
        'on-tertiary-container': '#a8abad',
        'on-primary-container': '#86b598',
        'inverse-surface': '#2f3131',
        'on-secondary-container': '#596376',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xs: '4px',
        margin: '32px',
        '2xl': '48px',
        base: '4px',
        xl: '32px',
        md: '16px',
        sm: '8px',
        '3xl': '64px',
        gutter: '24px',
        lg: '24px',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['IBM Plex Sans', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'display-lg': ['IBM Plex Sans', 'sans-serif'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'headline-md': ['IBM Plex Sans', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
